python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example0/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example0/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example0 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example1/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example1/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example1 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example2/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example2/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example2 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example3/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example3/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example3 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example4/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example4/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example4 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example5/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example5/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example5 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example6/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example6/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example6 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fq/example7/sample_R1_val_1.fq.gz -r2 /mnt/array2/pengxiang/annotation/reads/fq/example7/sample_R2_val_2.fq.gz -o /mnt/array2/pengxiang/annotation/pipeline1/run/fq/example7 -m -b -d -a

python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fa/example0/sample_R1.fa -r2 /mnt/array2/pengxiang/annotation/reads/fa/example0/sample_R2.fa -o /mnt/array2/pengxiang/annotation/pipeline1/run/fa/example0 -m -b -d -a
python3 pipeline1.py -r1 /mnt/array2/pengxiang/annotation/reads/fa/example8/sample_R1.fa -r2 /mnt/array2/pengxiang/annotation/reads/fa/example8/sample_R2.fa -o /mnt/array2/pengxiang/annotation/pipeline1/run/fa/example8 -m -b -d -a
